kind: pipeline
name: default

steps:
  - name: Critic
    depends_on:
      - clone
    image: gugod/perlcritic-reviewdog:latest
    commands:
      - perlcritic --quiet lib t dev-bin

  - name: Test
    depends_on:
      - clone
    image: perl:5.28.0
    commands:
      - cpanm -q --notest --no-man-pages --installdeps .
      - cpanm -q --notest --no-man-pages Test2::Harness
      - yath --qvf

  - name: Build
    image: perl:5.28.0
    depends_on:
      - Critic
      - Test
    commands:
      - cpanm -q --notest --no-man-pages App::ModuleBuildTiny Dist::Zilla Dist::Zilla::PluginBundle::RJBS
      - wget https://github.com/gugod/Software-License/archive/improve-cc0-detection.zip
      - unzip improve-cc0-detection.zip
      - cd Software-License-improve-cc0-detection
      - git init
      - git add .
      - git commit -m 'no comment'
      - git tag 0.103013
      - dzil install
      - cd ..
      - rm -rf Software-License-improve-cc0-detection
      - git clean -xdf
      - mbtiny dist
      - ls -l

  - &install_with_cpanm
    name: Install (perl 5.32)
    depends_on:
      - Build
    image: perl:5.32
    commands:
      - echo *.tar.gz
      - cpanm -q *.tar.gz

  - &install_with_cpanm
    name: Install (perl 5.30)
    depends_on:
      - Build
    image: perl:5.30
    commands:
      - echo *.tar.gz
      - cpanm -q *.tar.gz

  - <<: *install_with_cpanm
    name: Install (perl 5.28)
    image: perl:5.28

  - <<: *install_with_cpanm
    name: Install (perl 5.26)
    image: perl:5.26

  - <<: *install_with_cpanm
    name: Install (perl 5.18)
    image: perl:5.18
