language: perl
perl:
  - 5.30

before_install:
  - perl -V
  - cpanm -q --notest --no-man-pages App::ModuleBuildTiny Dist::Zilla Dist::Zilla::PluginBundle::RJBS
  - wget https://github.com/gugod/Software-License/archive/improve-cc0-detection.zip
  - unzip improve-cc0-detection.zip
  - cd Software-License-improve-cc0-detection
  - git init
  - git add .
  - git commit -m 'no comment'
  - git tag 0.103013
  - dzil install
  - cd ..
  - rm -rf Software-License-improve-cc0-detection
  - git clean -xdf
  - mbtiny dist

script:
  - echo *.tar.gz
  - cpanm --verbose *.tar.gz

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true

git:
  depth: 1
