name: test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "perl:5.32"
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: cpanm -q -n --no-man-pages --installdeps .
      - name: Install Test2::Harness
        run: cpanm -q -n --no-man-pages Test2::Harness
      - name: yath
        run: yath test --qvf
